import { Category, MarketplaceItem } from '../types';

// Research-backed marketplace seeds. Popularity numbers are curated from public lists/repo pages
// and used as "heat" indicators for demo ranking.
export const MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: 'awesome-claude-skills-composio',
    name: 'Awesome Claude Skills',
    description: '聚合 Claude 生态技能、资源与工具，适合快速发现可复用 skill。',
    category: '编程开发' as Category,
    tags: ['claude', 'skills', 'awesome', 'curated'],
    author: 'official',
    installs: 53400,
    githubPath: 'ComposioHQ/awesome-claude-skills',
    sourceType: 'github',
    sourceLabel: 'GitHub',
    sourceUrl: 'https://github.com/ComposioHQ/awesome-claude-skills',
    popularityLabel: '53.4k stars',
    trendNote: '热门榜单型仓库，覆盖面广',
  },
  {
    id: 'antigravity-awesome-skills',
    name: 'Antigravity Awesome Skills',
    description: '可安装的超大技能库，覆盖 Claude/Cursor/Codex 等多平台。',
    category: '效率流程' as Category,
    tags: ['multi-agent', 'catalog', 'installer', 'skill.md'],
    author: 'community',
    installs: 32500,
    githubPath: 'sickn33/antigravity-awesome-skills',
    sourceType: 'github',
    sourceLabel: 'GitHub',
    sourceUrl: 'https://github.com/sickn33/antigravity-awesome-skills',
    popularityLabel: '32.5k stars',
    trendNote: '安装体验完善，适合做“技能市场”演示',
  },
  {
    id: 'awesome-claude-subagents-voltagent',
    name: 'Awesome Claude Code Subagents',
    description: '面向 Claude Code 的子代理集合，便于团队分工协作。',
    category: '编程开发' as Category,
    tags: ['subagents', 'claude-code', 'team-workflow'],
    author: 'community',
    installs: 17100,
    githubPath: 'VoltAgent/awesome-claude-code-subagents',
    sourceType: 'github',
    sourceLabel: 'GitHub',
    sourceUrl: 'https://github.com/VoltAgent/awesome-claude-code-subagents',
    popularityLabel: '17.1k stars',
    trendNote: '子代理体系热门来源',
  },
  {
    id: 'awesome-agent-skills-voltagent',
    name: 'Awesome Agent Skills',
    description: '跨平台技能集合（Claude/Codex/Gemini/Cursor），强调通用兼容。',
    category: '效率流程' as Category,
    tags: ['agent-skills', 'cross-platform', 'catalog'],
    author: 'community',
    installs: 15400,
    githubPath: 'VoltAgent/awesome-agent-skills',
    sourceType: 'github',
    sourceLabel: 'GitHub',
    sourceUrl: 'https://github.com/VoltAgent/awesome-agent-skills',
    popularityLabel: '15.4k stars',
    trendNote: '适合做“跨平台来源”分组展示',
  },
  {
    id: 'agent-skills-addy',
    name: 'Agent Skills (Engineering)',
    description: '偏工程实战的技能集合，质量导向，适合研发团队落地。',
    category: '编程开发' as Category,
    tags: ['engineering', 'best-practice', 'production'],
    author: 'official',
    installs: 14100,
    githubPath: 'addyosmani/agent-skills',
    sourceType: 'github',
    sourceLabel: 'GitHub',
    sourceUrl: 'https://github.com/addyosmani/agent-skills',
    popularityLabel: '14.1k stars',
    trendNote: '工程向口碑仓库',
  },
  {
    id: 'awesome-claude-skills-travisvn',
    name: 'Awesome Claude Skills (Community)',
    description: '社区维护的 Claude skills 导航，适合快速选型与二次筛选。',
    category: '内容创作' as Category,
    tags: ['awesome-list', 'claude', 'discovery'],
    author: 'community',
    installs: 11100,
    githubPath: 'travisvn/awesome-claude-skills',
    sourceType: 'github',
    sourceLabel: 'GitHub',
    sourceUrl: 'https://github.com/travisvn/awesome-claude-skills',
    popularityLabel: '11.1k stars',
    trendNote: '适合内容/工作流方向技能发掘',
  },
  {
    id: 'awesome-claude-agents-vijay',
    name: 'Awesome Claude Agents',
    description: '聚焦 Agent/子代理实践，强调多角色协作与任务编排。',
    category: '产品设计' as Category,
    tags: ['agents', 'orchestration', 'claude'],
    author: 'community',
    installs: 4100,
    githubPath: 'vijaythecoder/awesome-claude-agents',
    sourceType: 'github',
    sourceLabel: 'GitHub',
    sourceUrl: 'https://github.com/vijaythecoder/awesome-claude-agents',
    popularityLabel: '4.1k stars',
    trendNote: '代理编排案例丰富',
  },
  {
    id: 'codex-skills-catalog',
    name: 'Codex Skills Catalog',
    description: '面向 Codex 的可安装技能目录，包含安装器与分层目录结构。',
    category: '数据分析' as Category,
    tags: ['codex', 'registry', 'installer', 'skill.md'],
    author: 'official',
    installs: 3600,
    githubPath: 'vadimcomanescu/codex-skills',
    sourceType: 'github',
    sourceLabel: 'GitHub',
    sourceUrl: 'https://github.com/vadimcomanescu/codex-skills',
    popularityLabel: 'curated catalog',
    trendNote: '适合做 Codex 技能导入演示',
  },
  {
    id: 'ok-skills',
    name: 'OK Skills',
    description: '支持 Codex/Claude/Cursor/OpenClaw 的通用 skills 与 playbooks。',
    category: '效率流程' as Category,
    tags: ['codex', 'cursor', 'claude', 'playbooks'],
    author: 'community',
    installs: 2900,
    githubPath: 'mxyhi/ok-skills',
    sourceType: 'github',
    sourceLabel: 'GitHub',
    sourceUrl: 'https://github.com/mxyhi/ok-skills',
    popularityLabel: 'multi-platform',
    trendNote: '跨工具兼容性强',
  },
  {
    id: 'cursor-marketplace-skill',
    name: 'Cursor Marketplace Skills',
    description: 'Cursor 官方技能市场入口，可作为“平台内技能商店”来源示例。',
    category: '商业营销' as Category,
    tags: ['cursor', 'marketplace', 'official'],
    author: 'official',
    installs: 2500,
    githubPath: 'cursor.com/marketplace/skills',
    sourceType: 'marketplace',
    sourceLabel: 'Cursor',
    sourceUrl: 'https://cursor.com/marketplace/skills',
    popularityLabel: 'official marketplace',
    trendNote: '适合展示“平台来源”入口',
  },
];
