import { MarketplaceItem } from '../types';

export const MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: 'git-ops',
    name: 'Git Ops',
    description: '处理提交、分支、冲突和回滚建议，让日常 Git 操作更稳更快。',
    category: '编程开发',
    tags: ['git', 'branch', 'commit', 'merge'],
    author: 'official',
    installs: 8420,
    githubPath: 'openai/skills/tree/main/skills/.curated/git-ops',
  },
  {
    id: 'code-review',
    name: 'Code Review',
    description: '做 PR 级别的代码审查，优先指出 bug、风险点和测试缺口。',
    category: '编程开发',
    tags: ['review', 'quality', 'security', 'testing'],
    author: 'official',
    installs: 6380,
    githubPath: 'openai/skills/tree/main/skills/.curated/code-review',
  },
  {
    id: 'api-docs',
    name: 'API Docs',
    description: '从接口定义或实现中整理出更适合交付和协作的 API 文档。',
    category: '编程开发',
    tags: ['api', 'docs', 'openapi', 'swagger'],
    author: 'community',
    installs: 3150,
    githubPath: 'openai/skills/tree/main/skills/.experimental/api-docs',
  },
  {
    id: 'web-search',
    name: 'Web Search',
    description: '联网检索最新公开信息并回收引用，适合调研、比价和事实核对。',
    category: '数据分析',
    tags: ['search', 'research', 'web', 'citations'],
    author: 'official',
    installs: 12600,
    githubPath: 'openai/skills/tree/main/skills/.curated/web-search',
  },
  {
    id: 'sql-analyst',
    name: 'SQL Analyst',
    description: '辅助写 SQL、调优查询和解释数据结果，适合分析型任务。',
    category: '数据分析',
    tags: ['sql', 'database', 'analytics', 'postgres'],
    author: 'official',
    installs: 5870,
    githubPath: 'openai/skills/tree/main/skills/.curated/sql-analyst',
  },
  {
    id: 'ux-research',
    name: 'UX Research',
    description: '帮助设计访谈提纲、可用性测试和研究总结，让产品判断更扎实。',
    category: '产品设计',
    tags: ['ux', 'research', 'usability', 'interview'],
    author: 'official',
    installs: 4120,
    githubPath: 'openai/skills/tree/main/skills/.curated/ux-research',
  },
  {
    id: 'meeting-notes',
    name: 'Meeting Notes',
    description: '快速整理会议纪要、决策记录和行动项，减少遗漏和重复沟通。',
    category: '效率流程',
    tags: ['meeting', 'summary', 'actions', 'notes'],
    author: 'official',
    installs: 9810,
    githubPath: 'openai/skills/tree/main/skills/.curated/meeting-notes',
  },
  {
    id: 'social-media',
    name: 'Social Media Copy',
    description: '为微博、公众号、LinkedIn 等平台生成更匹配语境的内容稿。',
    category: '商业营销',
    tags: ['social', 'content', 'growth', 'campaign'],
    author: 'official',
    installs: 5530,
    githubPath: 'openai/skills/tree/main/skills/.curated/social-media',
  },
];
